version: '3.8'
services:
  db:
    container_name: apexfit-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: apexuser
      POSTGRES_PASSWORD: apexpassword
      POSTGRES_DB: apexfit
    ports:
      - '5433:5432'
    volumes:
      - apexfit_pgdata:/var/lib/postgresql/data

volumes:
  apexfit_pgdata:
